export function getData() {
    return new Promise((resolve) => {
        // Simulamos un retraso de red de 500ms
        setTimeout(() => {
            resolve(
                [
                    { id: 0, label: 'Sin Intermediario' },
                    { id: 1, label: 'Operación Directa (OTC)' },
                    { id: 2, label: 'Kallpa Securities SAB' },
                    { id: 3, label: 'Credicorp Capital SAB' },
                    { id: 4, label: 'Inteligo SAB' },
                    { id: 5, label: 'Seminario y Cía. SAB' },
                    { id: 6, label: 'BTG Pactual Perú SAB' },
                    { id: 7, label: 'LarrainVial SAB' },
                    { id: 8, label: 'Scotia Bolsa' },
                    { id: 9, label: 'BBVA Bolsa' },
                    { id: 10, label: 'BNB Valores' },
                    { id: 11, label: 'Citigold' },
                    { id: 12, label: 'J.P. Morgan Securities' },
                    { id: 13, label: 'Goldman Sachs & Co.' },
                    { id: 14, label: 'Morgan Stanley' },
                    { id: 15, label: 'Merrill Lynch (BofA)' },
                    { id: 16, label: 'UBS AG' },
                    { id: 17, label: 'Credit Suisse' },
                    { id: 18, label: 'Deutsche Bank' },
                    { id: 19, label: 'Barclays Capital' },
                    { id: 20, label: 'HSBC Markets' },
                    { id: 21, label: 'Interactive Brokers' },
                    { id: 22, label: 'Charles Schwab' },
                    { id: 23, label: 'TD Ameritrade' },
                    { id: 24, label: 'E*TRADE' },
                    { id: 25, label: 'Saxo Bank' },
                    { id: 26, label: 'BNP Paribas' },
                    { id: 27, label: 'Société Générale' },
                    { id: 28, label: 'Santander Investment' },
                    { id: 29, label: 'Itaú BBA' },
                    { id: 30, label: 'Citigroup Global Markets' },
                    { id: 31, label: 'Fidelity Investments' },
                    { id: 32, label: 'Nomura Securities' },
                    { id: 33, label: 'Daiwa Capital Markets' },
                    { id: 34, label: 'Mizuho Securities' },
                    { id: 35, label: 'Standard Chartered' },
                    { id: 36, label: 'BMO Capital Markets' },
                    { id: 37, label: 'TD Securities' },
                    { id: 38, label: 'RBC Capital Markets' },
                    { id: 39, label: 'Commerzbank AG' },
                    { id: 40, label: 'Natixis' },
                    { id: 41, label: 'Jefferies LLC' },
                    { id: 42, label: 'Evercore' },
                    { id: 43, label: 'Lazard' },
                    { id: 44, label: 'Raymond James' },
                    { id: 45, label: 'Stifel Nicolaus' },
                    { id: 46, label: 'Piper Sandler' },
                    { id: 47, label: 'Cowen and Company' },
                    { id: 48, label: 'Houlihan Lokey' },
                    { id: 49, label: 'William Blair' },
                    { id: 50, label: 'Cantor Fitzgerald' },
                    { id: 51, label: 'BGC Partners' },
                    { id: 52, label: 'Tradeweb' },
                    { id: 53, label: 'TP ICAP' },
                    { id: 54, label: 'Marex Spectron' },
                    { id: 55, label: 'ADM Investor Services' },
                    { id: 56, label: 'StoneX Group' },
                    { id: 57, label: 'Sucden Financial' },
                    { id: 58, label: 'ED&F Man Capital Markets' },
                    { id: 59, label: 'Mayer Brown' },
                    { id: 60, label: 'BlackRock Execution Services' },
                    { id: 61, label: 'Vanguard Brokerage' },
                    { id: 62, label: 'State Street Global' },
                    { id: 63, label: 'Northern Trust' },
                    { id: 64, label: 'BNY Mellon Markets' },
                    { id: 65, label: 'Macquarie Group' },
                    { id: 66, label: 'ANZ Securities' },
                    { id: 67, label: 'Westpac Banking Corp' },
                    { id: 68, label: 'Commonwealth Bank' },
                    { id: 69, label: 'NAB Securities' },
                    { id: 70, label: 'DBS Vickers' },
                    { id: 71, label: 'OCBC Securities' },
                    { id: 72, label: 'UOB Kay Hian' },
                    { id: 73, label: 'Maybank Kim Eng' },
                    { id: 74, label: 'CIMB Securities' },
                    { id: 75, label: 'RHB Securities' },
                    { id: 76, label: 'China International Capital (CICC)' },
                    { id: 77, label: 'CITIC Securities' },
                    { id: 78, label: 'Huatai Securities' },
                    { id: 79, label: 'Guotai Junan Securities' },
                    { id: 80, label: 'Haitong Securities' },
                    { id: 81, label: 'Samsung Securities' },
                    { id: 82, label: 'Mirae Asset Securities' },
                    { id: 83, label: 'Korea Investment & Securities' },
                    { id: 84, label: 'NH Investment & Securities' },
                    { id: 85, label: 'KB Securities' },
                    { id: 86, label: 'Exotix Partners' },
                    { id: 87, label: 'Aura SAB' },
                    { id: 88, label: 'Cartisa Peru SAB' },
                    { id: 89, label: 'Diviso Bolsa SAB' },
                    { id: 90, label: 'Magot SAB' },
                    { id: 91, label: 'Renta 4 SAB' },
                    { id: 92, label: 'Sura SAB' },
                    { id: 93, label: 'Vargas y Peroni SAB' },
                    { id: 94, label: 'TradeStation' },
                    { id: 95, label: 'Plus500' },
                    { id: 96, label: 'IG Group' },
                    { id: 97, label: 'CMC Markets' },
                    { id: 98, label: 'Swissquote' },
                    { id: 99, label: 'Freedom Finance' },
                    { id: 100, label: 'Exante' }
                ]
            );
        }, 500);
    });
};
